apiVersion: v2
name: nodejs
version: 0.2.7
description: A Helm chart for NodeJS
type: application
keywords:
  - nodejs
home: https://github.com/shestera/charts
maintainers:
  - name: shestera
icon: https://helm.sh/img/helm-logo.svg
